from django import forms
from .models import Acessorios

# AQUI VAI CRIAR OS INPUTS DENTRO DO HTML

class EquipamentoForm(forms.ModelForm):
    class Meta:
        model = Acessorios
        fields = [
'peca',
'personagem',
'regenVida',
'regenMana',
'regenVigor',
'forca',
'destreza',
'inteligencia',
'determinacao',
'perspicacia',
'carisma',
'tipoRolagem_1',
'tipoRolagem_2',
'tipoRolagem_3',
'tipoRolagem_4',
'tipoRolagem_5',
'tipoRolagem_6',
'tipoRolagem_7',
'tipoRolagem_8',
'tipoRolagem_9',
'tipoRolagem_10',
'tipoRolagem_11',
'tipoRolagem_12',
'tipoRolagem_13',
'tipoRolagem_14',
'tipoRolagem_15',
'tipoRolagem_16',
'tipoRolagem_17',
'tipoRolagem_18',
'tipoRolagem_19',
'tipoRolagem_20',
'tipoRolagem_21',
'tipoRolagem_22',
'tipoRolagem_23',
'tipoRolagem_24',
'tipoRolagem_25',
'rolagem_1',
'rolagem_2',
'rolagem_3',
'rolagem_4',
'rolagem_5',
'rolagem_6',
'rolagem_7',
'rolagem_8',
'rolagem_9',
'rolagem_10',
'rolagem_11',
'rolagem_12',
'rolagem_13',
'rolagem_14',
'rolagem_15',
'rolagem_16',
'rolagem_17',
'rolagem_18',
'rolagem_19',
'rolagem_20',
'rolagem_21',
'rolagem_22',
'rolagem_23',
'rolagem_24',
'rolagem_25',
'elementoAmplificacao_1',
'elementoAmplificacao_2',
'elementoAmplificacao_3',
'elementoAmplificacao_4',
'elementoAmplificacao_5',
'elementoAmplificacao_6',
'elementoAmplificacao_7',
'elementoAmplificacao_8',
'elementoAmplificacao_9',
'elementoAmplificacao_10',
'elementoAmplificacao_11',
'elementoAmplificacao_12',
'elementoAmplificacao_13',
'elementoAmplificacao_14',
'elementoAmplificacao_15',
'elementoAmplificacao_16',
'elementoAmplificacao_17',
'elementoAmplificacao_18',
'elementoAmplificacao_19',
'elementoAmplificacao_20',
'elementoAmplificacao_21',
'elementoAmplificacao_22',
'elementoAmplificacao_23',
'elementoAmplificacao_24',
'elementoAmplificacao_25',
'amplificacao_1',
'amplificacao_2',
'amplificacao_3',
'amplificacao_4',
'amplificacao_5',
'amplificacao_6',
'amplificacao_7',
'amplificacao_8',
'amplificacao_9',
'amplificacao_10',
'amplificacao_11',
'amplificacao_12',
'amplificacao_13',
'amplificacao_14',
'amplificacao_15',
'amplificacao_16',
'amplificacao_17',
'amplificacao_18',
'amplificacao_19',
'amplificacao_20',
'amplificacao_21',
'amplificacao_22',
'amplificacao_23',
'amplificacao_24',
'amplificacao_25',
]

    widgets = {
        'tipo': forms.HiddenInput(), #Oculta o campo, pois já será preenchido
    }