# personagens/models.py
from django.db import models
from base_personagem.models import Base_personagem

class Tela_personagem(models.Model):
    personagem = models.ForeignKey(Base_personagem, on_delete=models.CASCADE)

    vida = models.IntegerField(default=100)
    regenVida = models.IntegerField(default=0)
    mana = models.IntegerField(default=100)
    regenMana = models.IntegerField(default=0)
    vigor = models.IntegerField(default=100)
    regenVigor = models.IntegerField(default=0)

    forca = models.IntegerField(default=0)
    destreza = models.IntegerField(default=0)
    inteligencia = models.IntegerField(default=0)
    determinacao = models.IntegerField(default=0)
    perspicacia = models.IntegerField(default=0)
    carisma = models.IntegerField(default=0)

    danoFixo_1 = models.IntegerField(default=0)
    penetracao_1 = models.IntegerField(default=0)
    danoFixo_2 = models.IntegerField(default=0)
    penetracao_2 = models.IntegerField(default=0)
    danoFixo_3 = models.IntegerField(default=0)
    penetracao_3 = models.IntegerField(default=0)
    dano_espiritual = models.IntegerField(default=0)
    danoFinal = models.IntegerField(default=0)
    penetracao_extra = models.IntegerField(default=0)
    
    defesaFixa_1 = models.IntegerField(default=0)
    resistencia_1 = models.IntegerField(default=0)
    defesaFixa_2 = models.IntegerField(default=0)
    resistencia_2 = models.IntegerField(default=0)
    defesaFixa_3 = models.IntegerField(default=0)
    resistencia_3 = models.IntegerField(default=0)
    defesaFixa_4 = models.IntegerField(default=0)
    resistencia_4 = models.IntegerField(default=0)
    defesaFixa_5 = models.IntegerField(default=0)
    resistencia_5 = models.IntegerField(default=0)
    reducao_espiritual = models.IntegerField(default=0)
    reducao = models.IntegerField(default=0)
    
    rolagem1 = models.IntegerField(default=0) 
    rolagem2 = models.IntegerField(default=0) 
    rolagem3 = models.IntegerField(default=0) 
    rolagem4 = models.IntegerField(default=0) 
    rolagem5 = models.IntegerField(default=0) 
    rolagem6 = models.IntegerField(default=0) 
    rolagem7 = models.IntegerField(default=0) 
    rolagem8 = models.IntegerField(default=0) 
    rolagem9 = models.IntegerField(default=0) 
    rolagem10 = models.IntegerField(default=0)    
    rolagem11 = models.IntegerField(default=0)    
    rolagem12 = models.IntegerField(default=0)    
    rolagem13 = models.IntegerField(default=0)    
    rolagem14 = models.IntegerField(default=0)   
    rolagem15 = models.IntegerField(default=0) 
    rolagem16 = models.IntegerField(default=0) 
    rolagem17 = models.IntegerField(default=0) 
    rolagem18 = models.IntegerField(default=0) 
    rolagem19 = models.IntegerField(default=0) 
    rolagem20 = models.IntegerField(default=0)    
    rolagem21 = models.IntegerField(default=0)    
    rolagem22 = models.IntegerField(default=0)    
    rolagem23 = models.IntegerField(default=0)    
    rolagem24 = models.IntegerField(default=0)    
    rolagem25 = models.IntegerField(default=0)   
    
    amplificacao1 = models.IntegerField(default=0)
    amplificacao2 = models.IntegerField(default=0)
    amplificacao3 = models.IntegerField(default=0)
    amplificacao4 = models.IntegerField(default=0)
    amplificacao5 = models.IntegerField(default=0)
    amplificacao6 = models.IntegerField(default=0)
    amplificacao7 = models.IntegerField(default=0)
    amplificacao8 = models.IntegerField(default=0)
    amplificacao9 = models.IntegerField(default=0)
    amplificacao10 = models.IntegerField(default=0)
    amplificacao11 = models.IntegerField(default=0)
    amplificacao12 = models.IntegerField(default=0)
    amplificacao13 = models.IntegerField(default=0)
    amplificacao14 = models.IntegerField(default=0)
    amplificacao15 = models.IntegerField(default=0)
    amplificacao15 = models.IntegerField(default=0)

    outros1 = models.IntegerField(default=0)
    outros2 = models.IntegerField(default=0)
    outros3 = models.IntegerField(default=0)
    outros4 = models.IntegerField(default=0)
    outros5 = models.IntegerField(default=0)
    outros6 = models.IntegerField(default=0)
    outros7 = models.IntegerField(default=0)
    outros8 = models.IntegerField(default=0)
    outros9 = models.IntegerField(default=0)
    outros10 = models.IntegerField(default=0)
    outros11 = models.IntegerField(default=0)
    outros12 = models.IntegerField(default=0)
    outros13 = models.IntegerField(default=0)
    outros14 = models.IntegerField(default=0)
    outros15 = models.IntegerField(default=0)

#    def __str__(self):
#        if self.personagem:
#            # Tenta usar o __str__ do modelo Personagem vinculado
#            return f"Base de Atributos para: {str(self.personagem)}"
#        else:
#            return "Base de Atributos (sem personagem vinculado)"
#
#    class Meta:
#        verbose_name = "Base de Atributos do Personagem"
#        verbose_name_plural = "Bases de Atributos dos Personagens"
    
class Elementos_personagem(models.Model):
    personagem = models.ForeignKey(Base_personagem, on_delete=models.CASCADE)

    danoFixo_1 = models.CharField(max_length=25, blank=True, default="")
    penetracao_1 = models.CharField(max_length=25, blank=True, default="")
    danoFixo_2 = models.CharField(max_length=25, blank=True, default="")
    penetracao_2 = models.CharField(max_length=25, blank=True, default="")
    danoFixo_3 = models.CharField(max_length=25, blank=True, default="")
    penetracao_3 = models.CharField(max_length=25, blank=True, default="")
    
    defesaFixa_1 = models.CharField(max_length=25, blank=True, default="")
    resistencia_1 = models.CharField(max_length=25, blank=True, default="")
    defesaFixa_2 = models.CharField(max_length=25, blank=True, default="")
    resistencia_2 = models.CharField(max_length=25, blank=True, default="")
    defesaFixa_3 = models.CharField(max_length=25, blank=True, default="")
    resistencia_3 = models.CharField(max_length=25, blank=True, default="")
    defesaFixa_4 = models.CharField(max_length=25, blank=True, default="")
    resistencia_4 = models.CharField(max_length=25, blank=True, default="")
    defesaFixa_5 = models.CharField(max_length=25, blank=True, default="")
    resistencia_5 = models.CharField(max_length=25, blank=True, default="")
    
    rolagem1 = models.CharField(max_length=25, blank=True, default="")
    rolagem2 = models.CharField(max_length=25, blank=True, default="")
    rolagem3 = models.CharField(max_length=25, blank=True, default="")
    rolagem4 = models.CharField(max_length=25, blank=True, default="")
    rolagem5 = models.CharField(max_length=25, blank=True, default="")
    rolagem6 = models.CharField(max_length=25, blank=True, default="")
    rolagem7 = models.CharField(max_length=25, blank=True, default="")
    rolagem8 = models.CharField(max_length=25, blank=True, default="")
    rolagem9 = models.CharField(max_length=25, blank=True, default="")
    rolagem10 = models.CharField(max_length=25, blank=True, default="")
    rolagem11 = models.CharField(max_length=25, blank=True, default="")
    rolagem12 = models.CharField(max_length=25, blank=True, default="")
    rolagem13 = models.CharField(max_length=25, blank=True, default="")
    rolagem14 = models.CharField(max_length=25, blank=True, default="")
    rolagem15 = models.CharField(max_length=25, blank=True, default="")
    rolagem16 = models.CharField(max_length=25, blank=True, default="")
    rolagem17 = models.CharField(max_length=25, blank=True, default="")
    rolagem18 = models.CharField(max_length=25, blank=True, default="")
    rolagem19 = models.CharField(max_length=25, blank=True, default="")
    rolagem20 = models.CharField(max_length=25, blank=True, default="")
    rolagem21 = models.CharField(max_length=25, blank=True, default="")
    rolagem22 = models.CharField(max_length=25, blank=True, default="")
    rolagem23 = models.CharField(max_length=25, blank=True, default="") 
    rolagem24 = models.CharField(max_length=25, blank=True, default="")  
    rolagem25 = models.CharField(max_length=25, blank=True, default="") 
    
    amplificacao1 = models.CharField(max_length=25, blank=True, default="")
    amplificacao2 = models.CharField(max_length=25, blank=True, default="")
    amplificacao3 = models.CharField(max_length=25, blank=True, default="")
    amplificacao4 = models.CharField(max_length=25, blank=True, default="")
    amplificacao5 = models.CharField(max_length=25, blank=True, default="")
    amplificacao6 = models.CharField(max_length=25, blank=True, default="")
    amplificacao7 = models.CharField(max_length=25, blank=True, default="")
    amplificacao8 = models.CharField(max_length=25, blank=True, default="")
    amplificacao9 = models.CharField(max_length=25, blank=True, default="")
    amplificacao10 = models.CharField(max_length=25, blank=True, default="")
    amplificacao11 = models.CharField(max_length=25, blank=True, default="")
    amplificacao12 = models.CharField(max_length=25, blank=True, default="")
    amplificacao13 = models.CharField(max_length=25, blank=True, default="")
    amplificacao14 = models.CharField(max_length=25, blank=True, default="")
    amplificacao15 = models.CharField(max_length=25, blank=True, default="")

    outros1 = models.CharField(max_length=25, blank=True, default="")
    outros2 = models.CharField(max_length=25, blank=True, default="")
    outros3 = models.CharField(max_length=25, blank=True, default="")
    outros4 = models.CharField(max_length=25, blank=True, default="")
    outros5 = models.CharField(max_length=25, blank=True, default="")
    outros6 = models.CharField(max_length=25, blank=True, default="")
    outros7 = models.CharField(max_length=25, blank=True, default="")
    outros8 = models.CharField(max_length=25, blank=True, default="")
    outros9 = models.CharField(max_length=25, blank=True, default="")
    outros10 = models.CharField(max_length=25, blank=True, default="")
    outros11 = models.CharField(max_length=25, blank=True, default="")
    outros12 = models.CharField(max_length=25, blank=True, default="")
    outros13 = models.CharField(max_length=25, blank=True, default="")
    outros14 = models.CharField(max_length=25, blank=True, default="")
    outros15 = models.CharField(max_length=25, blank=True, default="")
    
    #def __str__(self):
    #    return self.personagem