# Generated by Django 5.1.6 on 2025-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='dreno',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='arma',
            name='exaustao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='arma',
            name='murchamento',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
