# Generated by Django 5.1.6 on 2025-03-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arma',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='arma',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='arma',
            name='preco',
        ),
        migrations.AddField(
            model_name='arma',
            name='carisma',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='destreza',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='determinacao',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='forca',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='inteligencia',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='mana',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='perspicacia',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='vida',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='vigor',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='nome',
            field=models.CharField(default='', max_length=30),
        ),
    ]
