# Generated by Django 5.1.6 on 2025-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0002_rename_vida_arma_danofixo_2_remove_arma_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
