# Generated by Django 5.1.6 on 2025-04-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0002_alter_arma_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='elementoDano_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDano_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDano_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDano_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDano_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDano_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDano_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoPenetracao_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoPenetracao_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoPenetracao_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoPenetracao_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoPenetracao_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoPenetracao_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoPenetracao_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
