# Generated by Django 5.1.6 on 2025-03-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0002_remove_arma_descricao_remove_arma_estoque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='mana',
            new_name='danoFixo1',
        ),
        migrations.RemoveField(
            model_name='arma',
            name='vida',
        ),
        migrations.RemoveField(
            model_name='arma',
            name='vigor',
        ),
    ]
