# Generated by Django 5.1.6 on 2025-05-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0002_arma_dreno_arma_exaustao_arma_murchamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='vidaPer',
            new_name='vidaTotal',
        ),
    ]
