# Generated by Django 5.1.6 on 2025-03-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0003_rename_mana_arma_danofixo1_remove_arma_vida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='danoFixo1',
            new_name='danoFixo_1',
        ),
        migrations.AddField(
            model_name='arma',
            name='penetracao_1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='reducao',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='arma',
            name='vida',
            field=models.IntegerField(default='0'),
        ),
    ]
