# Generated by Django 5.1.6 on 2025-04-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0003_arma_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='elementoDefesa_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDefesa_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDefesa_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDefesa_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDefesa_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDefesa_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoDefesa_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoResistencia_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoResistencia_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoResistencia_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoResistencia_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoResistencia_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoResistencia_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='elementoResistencia_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
