# Generated by Django 5.1.6 on 2025-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(default='', max_length=100)),
                ('peca', models.CharField(choices=[('conjunto', 'Conjunto'), ('elmo', 'Elmo'), ('peitoral', 'Peitoral'), ('manoplas', 'Manoplas'), ('pernas', 'Calcas'), ('botas', 'Bota')], default='elmo', max_length=10)),
                ('nome', models.CharField(default='', max_length=30)),
                ('vida', models.IntegerField(blank=True, default=0)),
                ('forca', models.IntegerField(blank=True, default=0)),
                ('destreza', models.IntegerField(blank=True, default=0)),
                ('inteligencia', models.IntegerField(blank=True, default=0)),
                ('determinacao', models.IntegerField(blank=True, default=0)),
                ('perspicacia', models.IntegerField(blank=True, default=0)),
                ('carisma', models.IntegerField(blank=True, default=0)),
                ('defesaFixa_1', models.IntegerField(blank=True, default=0)),
                ('resistencia_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('reducao', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
