# Generated by Django 5.1.6 on 2025-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjunto',
            old_name='vida',
            new_name='defesaFixaEspiritual',
        ),
        migrations.RemoveField(
            model_name='conjunto',
            name='nome',
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_10',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_11',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_12',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_13',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_14',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_15',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_16',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_17',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_18',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_19',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_20',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_21',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_22',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_23',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_24',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_25',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_8',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='amplificacao_9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='defesaFixa_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='defesaFixa_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='defesaFixa_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='defesaFixa_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='defesaFixa_6',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='defesaFixa_7',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_16',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_17',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_18',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_19',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_20',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_21',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_22',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_23',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_24',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_25',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoAmplificacao_9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoDefesa_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoDefesa_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoDefesa_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoDefesa_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoDefesa_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoDefesa_6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoDefesa_7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoResistencia_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoResistencia_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoResistencia_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoResistencia_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoResistencia_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoResistencia_6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='elementoResistencia_7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='reducaoEspiritual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='regenMana',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='regenVida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='regenVigor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='resistencia_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='resistencia_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='resistencia_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='resistencia_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='resistencia_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='resistencia_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_16',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_17',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_18',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_19',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_20',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_21',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_22',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_23',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_24',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_25',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='rolagem_9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_16',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_17',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_18',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_19',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_20',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_21',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_22',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_23',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_24',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_25',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='tipoRolagem_9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='conjunto',
            name='peca',
            field=models.CharField(choices=[('conjunto', 'Conjunto'), ('elmo', 'Elmo'), ('peitoral', 'Peitoral'), ('manoplas', 'Manoplas'), ('pernas', 'Calcas'), ('botas', 'Bota')], default='principal', max_length=25),
        ),
    ]
