# Generated by Django 5.1.6 on 2025-04-08 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0001_initial'),
        ('conjunto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem'),
        ),
    ]
