# Generated by Django 5.1.6 on 2025-03-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0002_remove_conjunto_descricao_remove_conjunto_estoque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjunto',
            old_name='mana',
            new_name='defesaFixa_1',
        ),
        migrations.RenameField(
            model_name='conjunto',
            old_name='vigor',
            new_name='resistencia_1',
        ),
    ]
