# Generated by Django 5.1.6 on 2025-04-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0002_rename_vida_conjunto_defesafixaespiritual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
