# Generated by Django 5.1.6 on 2025-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0003_rename_mana_conjunto_defesafixa_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='reducao',
            field=models.IntegerField(default='0'),
        ),
    ]
