# Generated by Django 5.1.6 on 2025-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0003_conjunto_mana_conjunto_vida_conjunto_vidabase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='carismaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='destrezaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='determinacaoPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='forcaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='inteligenciaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conjunto',
            name='perspicaciaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='conjunto',
            name='reducao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='conjunto',
            name='reducaoEspiritual',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
