# Generated by Django 5.1.6 on 2025-03-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('resultado', models.IntegerField()),
            ],
        ),
    ]
