# Generated by Django 5.1.6 on 2025-05-10 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_personagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(choices=[('exemplar', 'Exemplar'), ('auxiliar', 'Auxiliar'), ('oficio', 'Oficio')], default='exemplar', max_length=25)),
                ('nome', models.CharField(default='', max_length=100)),
                ('vidaBase', models.IntegerField(blank=True, default=0)),
                ('vidaAtual', models.IntegerField(blank=True, default=0)),
                ('regenVida', models.IntegerField(blank=True, default=0)),
                ('mana', models.IntegerField(blank=True, default=0)),
                ('regenMana', models.IntegerField(blank=True, default=0)),
                ('vigor', models.IntegerField(blank=True, default=0)),
                ('regenVigor', models.IntegerField(blank=True, default=0)),
                ('forcaPer', models.IntegerField(blank=True, default=0)),
                ('destrezaPer', models.IntegerField(blank=True, default=0)),
                ('inteligenciaPer', models.IntegerField(blank=True, default=0)),
                ('determinacaoPer', models.IntegerField(blank=True, default=0)),
                ('perspicaciaPer', models.IntegerField(blank=True, default=0)),
                ('carismaPer', models.IntegerField(blank=True, default=0)),
                ('reducao', models.IntegerField(blank=True, default=0)),
                ('bloqueio', models.IntegerField(blank=True, default=0)),
                ('aumentoDA', models.IntegerField(blank=True, default=0)),
                ('reducaoEspiritual', models.IntegerField(blank=True, default=0)),
                ('esmagamento', models.IntegerField(blank=True, default=0)),
                ('penExtra', models.IntegerField(blank=True, default=0)),
                ('espiritualPerc', models.IntegerField(blank=True, default=0)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem')),
            ],
        ),
    ]
