# Generated by Django 5.1.6 on 2025-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestria',
            name='danoFinal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='maestria',
            name='dreno',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='maestria',
            name='espiritualFixo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='maestria',
            name='exaustao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='maestria',
            name='murchamento',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
