# Generated by Django 5.1.6 on 2025-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestria',
            old_name='danoFixo_6',
            new_name='aumentoDA',
        ),
        migrations.RenameField(
            model_name='maestria',
            old_name='danoFixo_7',
            new_name='bloqueio',
        ),
        migrations.RenameField(
            model_name='maestria',
            old_name='defesaFixaEspiritual',
            new_name='vidaAtual',
        ),
        migrations.RenameField(
            model_name='maestria',
            old_name='espiritualFixo',
            new_name='vidaBase',
        ),
        migrations.RemoveField(
            model_name='maestria',
            name='danoFinal',
        ),
        migrations.RemoveField(
            model_name='maestria',
            name='penetracao_6',
        ),
        migrations.RemoveField(
            model_name='maestria',
            name='penetracao_7',
        ),
        migrations.RemoveField(
            model_name='maestria',
            name='vida',
        ),
        migrations.AlterField(
            model_name='maestria',
            name='amplificacao_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='amplificacao_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='amplificacao_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='amplificacao_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='amplificacao_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='esmagamento',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='espiritualPerc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='penExtra',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='penetracao_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='penetracao_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='penetracao_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='penetracao_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='penetracao_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='reducao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='reducaoEspiritual',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='regenMana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='regenVida',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='regenVigor',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='resistencia_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='resistencia_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='resistencia_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='resistencia_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='resistencia_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='resistencia_6',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='resistencia_7',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
