# Generated by Django 5.1.6 on 2025-05-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_maestria_danofinal_maestria_dreno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestria',
            old_name='vidaAtual',
            new_name='vidaTotal',
        ),
    ]
