# Generated by Django 5.1.6 on 2025-04-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_danofixo_6_maestria_aumentoda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestria',
            old_name='carisma',
            new_name='carismaPer',
        ),
        migrations.RenameField(
            model_name='maestria',
            old_name='destreza',
            new_name='destrezaPer',
        ),
        migrations.RenameField(
            model_name='maestria',
            old_name='determinacao',
            new_name='determinacaoPer',
        ),
        migrations.RenameField(
            model_name='maestria',
            old_name='forca',
            new_name='forcaPer',
        ),
        migrations.RenameField(
            model_name='maestria',
            old_name='inteligencia',
            new_name='inteligenciaPer',
        ),
        migrations.RenameField(
            model_name='maestria',
            old_name='perspicacia',
            new_name='perspicaciaPer',
        ),
    ]
