from django import forms
from .models import Maestria

# AQUI VAI CRIAR OS INPUTS DENTRO DO HTML

class EquipamentoForm(forms.ModelForm):
    class Meta:
        model = Maestria
        fields = [
'peca',
'personagem',
'regenVida',
'regenMana',
'regenVigor',
'forcaPer',
'destrezaPer',
'inteligenciaPer',
'determinacaoPer',
'perspicaciaPer',
'carismaPer',
'tipoRolagem_1',
'tipoRolagem_2',
'tipoRolagem_3',
'tipoRolagem_4',
'tipoRolagem_5',
'rolagem_1',
'rolagem_2',
'rolagem_3',
'rolagem_4',
'rolagem_5',
'elementoDefesa_1',
'elementoDefesa_2',
'elementoDefesa_3',
'elementoDefesa_4',
'elementoDefesa_5',
'elementoResistencia_1',
'elementoResistencia_2',
'elementoResistencia_3',
'elementoResistencia_4',
'elementoResistencia_5',
'defesaFixa_1',
'defesaFixa_2',
'defesaFixa_3',
'defesaFixa_4',
'defesaFixa_5',
'resistencia_1',
'resistencia_2',
'resistencia_3',
'resistencia_4',
'resistencia_5',
'reducao',
'vidaAtual',
'reducaoEspiritual',
'elementoDano_1',
'elementoDano_2',
'elementoDano_3',
'elementoDano_4',
'elementoDano_5',
'elementoPenetracao_1',
'elementoPenetracao_2',
'elementoPenetracao_3',
'elementoPenetracao_4',
'elementoPenetracao_5',
'danoFixo_1',
'danoFixo_2',
'danoFixo_3',
'danoFixo_4',
'danoFixo_5',
'penetracao_1',
'penetracao_2',
'penetracao_3',
'penetracao_4',
'penetracao_5',
'esmagamento',
'penExtra',
'aumentoDA',
'espiritualPerc',
'vidaBase',
'elementoAmplificacao_1',
'elementoAmplificacao_2',
'elementoAmplificacao_3',
'elementoAmplificacao_4',
'elementoAmplificacao_5',
'amplificacao_1',
'amplificacao_2',
'amplificacao_3',
'amplificacao_4',
'amplificacao_5',
]
    widgets = {
        'tipo': forms.HiddenInput(), #Oculta o campo, pois já será preenchido
    }