# Generated by Django 5.1.6 on 2025-04-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(default='', max_length=100, unique=True)),
                ('vida', models.IntegerField(blank=True, default=0)),
                ('regenVida', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('mana', models.IntegerField(blank=True, default=0)),
                ('regenMana', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('vigor', models.IntegerField(blank=True, default=0)),
                ('regenVigor', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('forca', models.IntegerField(blank=True, default=0)),
                ('destreza', models.IntegerField(blank=True, default=0)),
                ('inteligencia', models.IntegerField(blank=True, default=0)),
                ('determinacao', models.IntegerField(blank=True, default=0)),
                ('perspicacia', models.IntegerField(blank=True, default=0)),
                ('carisma', models.IntegerField(blank=True, default=0)),
                ('tipoRolagem_1', models.CharField(default='', max_length=100)),
                ('tipoRolagem_2', models.CharField(default='', max_length=100)),
                ('tipoRolagem_3', models.CharField(default='', max_length=100)),
                ('tipoRolagem_4', models.CharField(default='', max_length=100)),
                ('tipoRolagem_5', models.CharField(default='', max_length=100)),
                ('rolagem_1', models.IntegerField(blank=True, default=0)),
                ('rolagem_2', models.IntegerField(blank=True, default=0)),
                ('rolagem_3', models.IntegerField(blank=True, default=0)),
                ('rolagem_4', models.IntegerField(blank=True, default=0)),
                ('rolagem_5', models.IntegerField(blank=True, default=0)),
                ('elementoDefesa_1', models.CharField(default='', max_length=100)),
                ('elementoDefesa_2', models.CharField(default='', max_length=100)),
                ('elementoDefesa_3', models.CharField(default='', max_length=100)),
                ('elementoResistencia_1', models.CharField(default='', max_length=100)),
                ('elementoResistencia_2', models.CharField(default='', max_length=100)),
                ('elementoResistencia_3', models.CharField(default='', max_length=100)),
                ('defesaFixa_1', models.IntegerField(blank=True, default=0)),
                ('defesaFixa_2', models.IntegerField(blank=True, default=0)),
                ('defesaFixa_3', models.IntegerField(blank=True, default=0)),
                ('resistencia_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('resistencia_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('resistencia_3', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('reducao', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('elementoDano_1', models.CharField(default='', max_length=100)),
                ('elementoDano_2', models.CharField(default='', max_length=100)),
                ('elementoDano_3', models.CharField(default='', max_length=100)),
                ('elementoPenetracao_1', models.CharField(default='', max_length=100)),
                ('elementoPenetracao_2', models.CharField(default='', max_length=100)),
                ('elementoPenetracao_3', models.CharField(default='', max_length=100)),
                ('danoFixo_1', models.IntegerField(blank=True, default=0)),
                ('danoFixo_2', models.IntegerField(blank=True, default=0)),
                ('danoFixo_3', models.IntegerField(blank=True, default=0)),
                ('penetracao_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('penetracao_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('penetracao_3', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('danoFinal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('elementoAmplificacao_1', models.CharField(default='', max_length=100)),
                ('elementoAmplificacao_2', models.CharField(default='', max_length=100)),
                ('elementoAmplificacao_3', models.CharField(default='', max_length=100)),
                ('elementoAmplificacao_4', models.CharField(default='', max_length=100)),
                ('elementoAmplificacao_5', models.CharField(default='', max_length=100)),
                ('amplificacao_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('amplificacao_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('amplificacao_3', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('amplificacao_4', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('amplificacao_5', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
