# Generated by Django 5.1.6 on 2025-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('vida', models.IntegerField(default='0')),
                ('mana', models.IntegerField(default='0')),
                ('vigor', models.IntegerField(default='0')),
                ('forca', models.IntegerField(default='0')),
                ('destreza', models.IntegerField(default='0')),
                ('inteligencia', models.IntegerField(default='0')),
                ('determinacao', models.IntegerField(default='0')),
                ('perspicacia', models.IntegerField(default='0')),
                ('carisma', models.IntegerField(default='0')),
            ],
        ),
    ]
