# Generated by Django 5.1.6 on 2025-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(default='', max_length=100, unique=True)),
                ('vida', models.IntegerField(blank=True, default=100)),
                ('vidaBase', models.IntegerField(blank=True, default=0)),
                ('regenVida', models.IntegerField(blank=True, default=0)),
                ('mana', models.IntegerField(blank=True, default=100)),
                ('regenMana', models.IntegerField(blank=True, default=0)),
                ('vigor', models.IntegerField(blank=True, default=100)),
                ('regenVigor', models.IntegerField(blank=True, default=0)),
                ('forca', models.IntegerField(blank=True, default=0)),
                ('destreza', models.IntegerField(blank=True, default=0)),
                ('inteligencia', models.IntegerField(blank=True, default=0)),
                ('determinacao', models.IntegerField(blank=True, default=0)),
                ('perspicacia', models.IntegerField(blank=True, default=0)),
                ('carisma', models.IntegerField(blank=True, default=0)),
                ('forcaPer', models.IntegerField(blank=True, default=0)),
                ('destrezaPer', models.IntegerField(blank=True, default=0)),
                ('inteligenciaPer', models.IntegerField(blank=True, default=0)),
                ('determinacaoPer', models.IntegerField(blank=True, default=0)),
                ('perspicaciaPer', models.IntegerField(blank=True, default=0)),
                ('carismaPer', models.IntegerField(blank=True, default=0)),
                ('reducao', models.IntegerField(blank=True, default=0)),
                ('defesaFixaEspiritual', models.IntegerField(blank=True, default=0)),
                ('reducaoEspiritual', models.IntegerField(blank=True, default=0)),
                ('esmagamento', models.IntegerField(blank=True, default=0)),
                ('penExtra', models.IntegerField(blank=True, default=0)),
                ('danoFinal', models.IntegerField(blank=True, default=0)),
                ('espiritualPerc', models.IntegerField(blank=True, default=0)),
                ('espiritualFixo', models.IntegerField(blank=True, default=0)),
                ('dreno', models.IntegerField(blank=True, default=0)),
                ('exaustao', models.IntegerField(blank=True, default=0)),
                ('murchamento', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
