# Generated by Django 5.1.6 on 2025-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_personagem',
            name='nome',
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='amplificacao_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='amplificacao_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='amplificacao_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='amplificacao_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='amplificacao_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='danoFinal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='danoFixo_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='danoFixo_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='danoFixo_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='defesaFixa_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='defesaFixa_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='defesaFixa_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoAmplificacao_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoAmplificacao_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoAmplificacao_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoAmplificacao_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoAmplificacao_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoDano_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoDano_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoDano_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoDefesa_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoDefesa_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoDefesa_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoPenetracao_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoPenetracao_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoPenetracao_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoResistencia_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoResistencia_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='elementoResistencia_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='penetracao_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='penetracao_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='penetracao_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='personagem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='reducao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='regenMana',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='regenVida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='regenVigor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='resistencia_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='resistencia_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='resistencia_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='rolagem_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='rolagem_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='rolagem_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='rolagem_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='rolagem_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='tipoRolagem_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='tipoRolagem_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='tipoRolagem_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='tipoRolagem_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='tipoRolagem_5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='carisma',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='destreza',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='determinacao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='forca',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='inteligencia',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='mana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='perspicacia',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='vida',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='vigor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
