# Generated by Django 5.1.6 on 2025-05-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_personagem',
            name='vida',
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='vidaFixaBase',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
