# Generated by Django 5.1.6 on 2025-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0002_remove_base_personagem_vida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personagem',
            name='vidaFixaBase',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
