# Generated by Django 5.1.6 on 2025-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0002_remove_base_personagem_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personagem',
            name='personagem',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
