# Generated by Django 5.1.6 on 2025-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0002_alter_base_personagem_rolagem_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_personagem',
            name='carismaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='destrezaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='determinacaoPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='forcaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='inteligenciaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='base_personagem',
            name='perspicaciaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
