# Generated by Django 5.1.6 on 2025-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0003_base_personagem_mana_base_personagem_vidabase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personagem',
            name='reducao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='reducaoEspiritual',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
