# Generated by Django 5.1.6 on 2025-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0004_alter_base_personagem_reducao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_personagem',
            name='mana',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='vida',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='base_personagem',
            name='vigor',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
