from django.db import models
from base_personagem.models import Base_personagem

class Habilidade(models.Model):
    # NOME DO PERSONAGEM
    personagem = models.ForeignKey(Base_personagem, on_delete=models.CASCADE)

    hab1_1_descricao = models.TextField(default="", blank=True)
    hab1_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab1_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab1_2_descricao = models.TextField(default="", blank=True)
    hab1_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab1_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab1_3_descricao = models.TextField(default="", blank=True)
    hab1_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab1_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab1_4_descricao = models.TextField(default="", blank=True)
    hab1_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab1_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab1_5_descricao = models.TextField(default="", blank=True)
    hab1_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab1_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab1_6_descricao = models.TextField(default="", blank=True)
    hab1_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab1_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 2
    hab2_1_descricao = models.TextField(default="", blank=True)
    hab2_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab2_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab2_2_descricao = models.TextField(default="", blank=True)
    hab2_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab2_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab2_3_descricao = models.TextField(default="", blank=True)
    hab2_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab2_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab2_4_descricao = models.TextField(default="", blank=True)
    hab2_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab2_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab2_5_descricao = models.TextField(default="", blank=True)
    hab2_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab2_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab2_6_descricao = models.TextField(default="", blank=True)
    hab2_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab2_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 3
    hab3_1_descricao = models.TextField(default="", blank=True)
    hab3_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab3_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab3_2_descricao = models.TextField(default="", blank=True)
    hab3_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab3_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab3_3_descricao = models.TextField(default="", blank=True)
    hab3_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab3_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab3_4_descricao = models.TextField(default="", blank=True)
    hab3_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab3_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab3_5_descricao = models.TextField(default="", blank=True)
    hab3_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab3_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab3_6_descricao = models.TextField(default="", blank=True)
    hab3_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab3_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 4
    hab4_1_descricao = models.TextField(default="", blank=True)
    hab4_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab4_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab4_2_descricao = models.TextField(default="", blank=True)
    hab4_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab4_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab4_3_descricao = models.TextField(default="", blank=True)
    hab4_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab4_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab4_4_descricao = models.TextField(default="", blank=True)
    hab4_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab4_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab4_5_descricao = models.TextField(default="", blank=True)
    hab4_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab4_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab4_6_descricao = models.TextField(default="", blank=True)
    hab4_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab4_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 5
    hab5_1_descricao = models.TextField(default="", blank=True)
    hab5_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab5_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab5_2_descricao = models.TextField(default="", blank=True)
    hab5_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab5_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab5_3_descricao = models.TextField(default="", blank=True)
    hab5_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab5_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab5_4_descricao = models.TextField(default="", blank=True)
    hab5_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab5_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab5_5_descricao = models.TextField(default="", blank=True)
    hab5_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab5_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab5_6_descricao = models.TextField(default="", blank=True)
    hab5_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab5_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 7 (Nota: pulou do 5 para o 7 no seu comentário original)
    hab6_1_descricao = models.TextField(default="", blank=True)
    hab6_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab6_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab6_2_descricao = models.TextField(default="", blank=True)
    hab6_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab6_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab6_3_descricao = models.TextField(default="", blank=True)
    hab6_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab6_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab6_4_descricao = models.TextField(default="", blank=True)
    hab6_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab6_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab6_5_descricao = models.TextField(default="", blank=True)
    hab6_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab6_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab6_6_descricao = models.TextField(default="", blank=True)
    hab6_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab6_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 8
    hab7_1_descricao = models.TextField(default="", blank=True)
    hab7_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab7_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab7_2_descricao = models.TextField(default="", blank=True)
    hab7_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab7_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab7_3_descricao = models.TextField(default="", blank=True)
    hab7_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab7_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab7_4_descricao = models.TextField(default="", blank=True)
    hab7_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab7_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab7_5_descricao = models.TextField(default="", blank=True)
    hab7_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab7_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab7_6_descricao = models.TextField(default="", blank=True)
    hab7_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab7_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 8 (Repetido no comentário original)
    hab8_1_descricao = models.TextField(default="", blank=True)
    hab8_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab8_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab8_2_descricao = models.TextField(default="", blank=True)
    hab8_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab8_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab8_3_descricao = models.TextField(default="", blank=True)
    hab8_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab8_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab8_4_descricao = models.TextField(default="", blank=True)
    hab8_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab8_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab8_5_descricao = models.TextField(default="", blank=True)
    hab8_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab8_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab8_6_descricao = models.TextField(default="", blank=True)
    hab8_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab8_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 9
    hab9_1_descricao = models.TextField(default="", blank=True)
    hab9_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab9_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab9_2_descricao = models.TextField(default="", blank=True)
    hab9_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab9_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab9_3_descricao = models.TextField(default="", blank=True)
    hab9_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab9_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab9_4_descricao = models.TextField(default="", blank=True)
    hab9_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab9_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab9_5_descricao = models.TextField(default="", blank=True)
    hab9_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab9_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab9_6_descricao = models.TextField(default="", blank=True)
    hab9_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab9_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 10
    hab10_1_descricao = models.TextField(default="", blank=True)
    hab10_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab10_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab10_2_descricao = models.TextField(default="", blank=True)
    hab10_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab10_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab10_3_descricao = models.TextField(default="", blank=True)
    hab10_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab10_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab10_4_descricao = models.TextField(default="", blank=True)
    hab10_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab10_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab10_5_descricao = models.TextField(default="", blank=True)
    hab10_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab10_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab10_6_descricao = models.TextField(default="", blank=True)
    hab10_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab10_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 11
    hab11_1_descricao = models.TextField(default="", blank=True)
    hab11_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab11_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab11_2_descricao = models.TextField(default="", blank=True)
    hab11_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab11_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab11_3_descricao = models.TextField(default="", blank=True)
    hab11_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab11_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab11_4_descricao = models.TextField(default="", blank=True)
    hab11_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab11_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab11_5_descricao = models.TextField(default="", blank=True)
    hab11_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab11_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab11_6_descricao = models.TextField(default="", blank=True)
    hab11_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab11_6_custo = models.CharField(max_length=70, default="", blank=True)
    # HABILIDADE 12
    hab12_1_descricao = models.TextField(default="", blank=True)
    hab12_1_nome = models.CharField(max_length=70, default="", blank=True)
    hab12_1_custo = models.CharField(max_length=70, default="", blank=True)
    hab12_2_descricao = models.TextField(default="", blank=True)
    hab12_2_nome = models.CharField(max_length=70, default="", blank=True)
    hab12_2_custo = models.CharField(max_length=70, default="", blank=True)
    hab12_3_descricao = models.TextField(default="", blank=True)
    hab12_3_nome = models.CharField(max_length=70, default="", blank=True)
    hab12_3_custo = models.CharField(max_length=70, default="", blank=True)
    hab12_4_descricao = models.TextField(default="", blank=True)
    hab12_4_nome = models.CharField(max_length=70, default="", blank=True)
    hab12_4_custo = models.CharField(max_length=70, default="", blank=True)
    hab12_5_descricao = models.TextField(default="", blank=True)
    hab12_5_nome = models.CharField(max_length=70, default="", blank=True)
    hab12_5_custo = models.CharField(max_length=70, default="", blank=True)
    hab12_6_descricao = models.TextField(default="", blank=True)
    hab12_6_nome = models.CharField(max_length=70, default="", blank=True)
    hab12_6_custo = models.CharField(max_length=70, default="", blank=True)

    def __str__(self):
        return self.personagem