# Generated by Django 5.1.6 on 2025-03-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tela_personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Aryah Astaris', max_length=200)),
                ('vida', models.CharField(default='307.481 [614.962]', max_length=50)),
                ('mana', models.CharField(default='135 [243]', max_length=50)),
                ('vigor', models.CharField(default='125 [225]', max_length=50)),
                ('forca', models.CharField(default='650 +6', max_length=50)),
                ('destreza', models.CharField(default='650 +6', max_length=50)),
                ('inteligencia', models.CharField(default='3.000 +40', max_length=50)),
                ('determinacao', models.CharField(default='10.062 +100', max_length=50)),
                ('perspicacia', models.CharField(default='2.710 +27', max_length=50)),
                ('carisma', models.CharField(default='1.821 +18', max_length=50)),
                ('dano_fixo_solar', models.CharField(default='154.324', max_length=50)),
                ('penetracao_solar', models.CharField(default='90%', max_length=50)),
                ('dano_fixo_sacrosolar', models.CharField(default='20', max_length=50)),
                ('dano_final', models.CharField(default='10%', max_length=50)),
                ('defesa_fixa_chaos', models.CharField(default='10.000', max_length=50)),
                ('resistencia_chaos', models.CharField(default='90%', max_length=50)),
                ('defesa_fixa_espiritual', models.CharField(default='1.150', max_length=50)),
                ('reducao_espiritual', models.CharField(default='60%', max_length=50)),
                ('resistencia_necrotica', models.CharField(default='25%', max_length=50)),
                ('rolagem_invocacao', models.CharField(default='10', max_length=50)),
                ('rolagem_cura', models.CharField(default='10', max_length=50)),
                ('rolagem_curado', models.CharField(default='10', max_length=50)),
                ('rolagem_aprimoramento', models.CharField(default='10', max_length=50)),
                ('rolagem_magias_solares', models.CharField(default='10', max_length=50)),
                ('rolagem_magias_diversas', models.CharField(default='10', max_length=50)),
                ('amplificacao_solar', models.CharField(default='10', max_length=50)),
                ('amplificacao_sacrosolar', models.CharField(default='10', max_length=50)),
                ('suporte', models.CharField(default='Suporte', max_length=50)),
                ('amplificacao_cura', models.CharField(default='10', max_length=50)),
                ('amplificacao_escudo', models.CharField(default='10', max_length=50)),
                ('amplificacao_aprimoramento', models.CharField(default='10', max_length=50)),
                ('amplificacao_debilidades', models.CharField(default='10', max_length=50)),
                ('cavalheiras', models.CharField(default='Cavalheiras', max_length=50)),
                ('amplificacao_invocacao', models.CharField(default='10', max_length=50)),
                ('reducao_murchamento_vital', models.CharField(default='5%', max_length=50)),
            ],
        ),
    ]
