# Generated by Django 5.1.6 on 2025-05-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_personagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavelTipo', models.CharField(blank=True, default='', max_length=50)),
                ('variavelPropriedade', models.CharField(blank=True, default='', max_length=50)),
                ('variavelValor', models.IntegerField(blank=True, default=0)),
                ('posicao', models.IntegerField()),
                ('peca', models.CharField(blank=True, default='', max_length=50)),
                ('origem', models.CharField(blank=True, default='', max_length=50)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Character_effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavelTipo', models.CharField(blank=True, default='', max_length=50)),
                ('variavelNome', models.CharField(blank=True, default='', max_length=50)),
                ('variavelDescricao', models.CharField(blank=True, default='', max_length=1000)),
                ('posicao', models.IntegerField()),
                ('peca', models.CharField(blank=True, default='', max_length=50)),
                ('origem', models.CharField(blank=True, default='', max_length=50)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Tela_personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=25)),
                ('vida', models.IntegerField(blank=True, default=100)),
                ('mana', models.IntegerField(blank=True, default=100)),
                ('vigor', models.IntegerField(blank=True, default=100)),
                ('vidaTotalCalc', models.IntegerField(blank=True, default=0)),
                ('vidaBaseCalc', models.IntegerField(blank=True, default=0)),
                ('regenVida', models.IntegerField(blank=True, default=0)),
                ('regenMana', models.IntegerField(blank=True, default=0)),
                ('regenVigor', models.IntegerField(blank=True, default=0)),
                ('forca', models.IntegerField(blank=True, default=0)),
                ('destreza', models.IntegerField(blank=True, default=0)),
                ('inteligencia', models.IntegerField(blank=True, default=0)),
                ('determinacao', models.IntegerField(blank=True, default=0)),
                ('perspicacia', models.IntegerField(blank=True, default=0)),
                ('carisma', models.IntegerField(blank=True, default=0)),
                ('forcaPer', models.IntegerField(blank=True, default=0)),
                ('destrezaPer', models.IntegerField(blank=True, default=0)),
                ('inteligenciaPer', models.IntegerField(blank=True, default=0)),
                ('determinacaoPer', models.IntegerField(blank=True, default=0)),
                ('perspicaciaPer', models.IntegerField(blank=True, default=0)),
                ('carismaPer', models.IntegerField(blank=True, default=0)),
                ('forcaTotal', models.IntegerField(blank=True, default=0)),
                ('destrezaTotal', models.IntegerField(blank=True, default=0)),
                ('inteligenciaTotal', models.IntegerField(blank=True, default=0)),
                ('determinacaoTotal', models.IntegerField(blank=True, default=0)),
                ('perspicaciaTotal', models.IntegerField(blank=True, default=0)),
                ('carismaTotal', models.IntegerField(blank=True, default=0)),
                ('reducao', models.IntegerField(blank=True, default=0)),
                ('defesaFixaEspiritual', models.IntegerField(blank=True, default=0)),
                ('reducaoEspiritual', models.IntegerField(blank=True, default=0)),
                ('esmagamento', models.IntegerField(blank=True, default=0)),
                ('penExtra', models.IntegerField(blank=True, default=0)),
                ('danoFinal', models.IntegerField(blank=True, default=0)),
                ('espiritualPerc', models.IntegerField(blank=True, default=0)),
                ('espiritualFixo', models.IntegerField(blank=True, default=0)),
                ('dreno', models.IntegerField(blank=True, default=0)),
                ('exaustao', models.IntegerField(blank=True, default=0)),
                ('murchamento', models.IntegerField(blank=True, default=0)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem')),
            ],
        ),
    ]
