# Generated by Django 5.1.6 on 2025-05-10 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_personagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavelTipo', models.CharField(blank=True, default='', max_length=50)),
                ('variavelPropriedade', models.CharField(blank=True, default='', max_length=50)),
                ('variavelValor', models.IntegerField(blank=True, default=0)),
                ('posicao', models.IntegerField()),
                ('peca', models.CharField(blank=True, default='', max_length=50)),
                ('origem', models.CharField(blank=True, default='', max_length=50)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Tela_personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=25)),
                ('vida', models.IntegerField(blank=True, default=100)),
                ('mana', models.IntegerField(blank=True, default=100)),
                ('vigor', models.IntegerField(blank=True, default=100)),
                ('regenVida', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('regenMana', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('regenVigor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('forca', models.IntegerField(blank=True, default=0)),
                ('destreza', models.IntegerField(blank=True, default=0)),
                ('inteligencia', models.IntegerField(blank=True, default=0)),
                ('determinacao', models.IntegerField(blank=True, default=0)),
                ('perspicacia', models.IntegerField(blank=True, default=0)),
                ('carisma', models.IntegerField(blank=True, default=0)),
                ('forcaPer', models.IntegerField(blank=True, default=0)),
                ('destrezaPer', models.IntegerField(blank=True, default=0)),
                ('inteligenciaPer', models.IntegerField(blank=True, default=0)),
                ('determinacaoPer', models.IntegerField(blank=True, default=0)),
                ('perspicaciaPer', models.IntegerField(blank=True, default=0)),
                ('carismaPer', models.IntegerField(blank=True, default=0)),
                ('reducao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('defesaFixaEspiritual', models.IntegerField(blank=True, default=0)),
                ('reducaoEspiritual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('esmagamento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('penExtra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('danoFinal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('espiritualPerc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('espiritualFixo', models.IntegerField(blank=True, default=0)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem')),
            ],
        ),
    ]
