# Generated by Django 5.1.6 on 2025-05-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='vidaBaseCalc',
            new_name='vidaFixaBase',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='vidaTotalCalc',
        ),
    ]
