# Generated by Django 5.1.6 on 2025-04-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementos_personagem',
            old_name='nome',
            new_name='personagem',
        ),
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='nome',
            new_name='personagem',
        ),
    ]
