# Generated by Django 5.1.6 on 2025-05-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='dreno',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='exaustao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='murchamento',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='danoFinal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='esmagamento',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='espiritualPerc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='penExtra',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
