# Generated by Django 5.1.6 on 2025-04-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao1',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao10',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao11',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao12',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao13',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao14',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao15',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao2',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao3',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao4',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao5',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao6',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao7',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao8',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='amplificacao9',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='dano_espiritual',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='mana',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros1',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros10',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros11',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros12',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros13',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros14',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros15',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros2',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros3',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros4',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros5',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros6',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros7',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros8',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='outros9',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='penetracao_extra',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='reducao_espiritual',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem1',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem10',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem11',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem12',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem13',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem14',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem15',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem16',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem17',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem18',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem19',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem2',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem20',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem21',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem22',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem23',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem24',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem25',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem3',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem4',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem5',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem6',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem7',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem8',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='rolagem9',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='vida',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='vigor',
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_10',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_11',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_12',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_13',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_14',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_15',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_16',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_17',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_18',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_19',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_20',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_21',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_22',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_23',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_24',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_25',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_8',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao_9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='danoFixo_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='danoFixo_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='danoFixo_6',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='danoFixo_7',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='defesaFixaEspiritual',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='defesaFixa_6',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='defesaFixa_7',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_16',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_17',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_18',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_19',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_20',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_21',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_22',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_23',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_24',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_25',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoAmplificacao_9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDano_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDano_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDano_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDano_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDano_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDano_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDano_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDefesa_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDefesa_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDefesa_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDefesa_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDefesa_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDefesa_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoDefesa_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoPenetracao_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoPenetracao_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoPenetracao_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoPenetracao_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoPenetracao_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoPenetracao_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoPenetracao_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoResistencia_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoResistencia_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoResistencia_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoResistencia_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoResistencia_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoResistencia_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='elementoResistencia_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='esmagamento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='espiritualFixo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='espiritualPerc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penExtra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='reducaoEspiritual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='resistencia_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='resistencia_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_16',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_17',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_18',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_19',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_20',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_21',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_22',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_23',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_24',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_25',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem_9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_16',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_17',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_18',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_19',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_20',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_21',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_22',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_23',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_24',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_25',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='tipoRolagem_9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='carisma',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='danoFinal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='danoFixo_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='danoFixo_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='danoFixo_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='defesaFixa_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='defesaFixa_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='defesaFixa_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='defesaFixa_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='defesaFixa_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='destreza',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='determinacao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='forca',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='inteligencia',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='penetracao_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='penetracao_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='penetracao_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='perspicacia',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='reducao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenMana',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenVida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenVigor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='resistencia_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='resistencia_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='resistencia_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='resistencia_4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='resistencia_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Elementos_personagem',
        ),
    ]
