# Generated by Django 5.1.6 on 2025-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0002_remove_tela_personagem_amplificacao_aprimoramento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='danoFixo1',
            field=models.IntegerField(default='0'),
        ),
    ]
