# Generated by Django 5.1.6 on 2025-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0002_tela_personagem_dreno_tela_personagem_exaustao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela_personagem',
            name='reducao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='reducaoEspiritual',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenMana',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenVida',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenVigor',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
