# Generated by Django 5.1.6 on 2025-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0002_remove_tela_personagem_amplificacao1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='mana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='vida',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='vigor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
