# Generated by Django 5.1.6 on 2025-05-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0004_alter_base_personagem_reducao_and_more'),
        ('tela_personagem', '0003_alter_tela_personagem_reducao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavelTipo', models.CharField(blank=True, default='', max_length=50)),
                ('variavelNome', models.CharField(blank=True, default='', max_length=50)),
                ('variavelDescricao', models.IntegerField(blank=True, default=0)),
                ('posicao', models.IntegerField()),
                ('peca', models.CharField(blank=True, default='', max_length=50)),
                ('origem', models.CharField(blank=True, default='', max_length=50)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem')),
            ],
        ),
    ]
