# Generated by Django 5.1.6 on 2025-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0003_tela_personagem_vidafinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='vidaBase',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='vidaTotal',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
