# Generated by Django 5.1.6 on 2025-03-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0003_tela_personagem_danofixo1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='danoFixo1',
            new_name='danoFixo_1',
        ),
    ]
