# Generated by Django 5.1.6 on 2025-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0004_tela_personagem_vidabase_tela_personagem_vidatotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela_personagem',
            name='mana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vida',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vidaBase',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vidaFinal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vidaTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vigor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
