# Generated by Django 5.1.6 on 2025-03-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0004_rename_danofixo1_tela_personagem_danofixo_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='danoFixo_2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='danoFixo_3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_3',
            field=models.IntegerField(default='0'),
        ),
    ]
