# Generated by Django 5.1.6 on 2025-05-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0004_character_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='carismaTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='destrezaTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='determinacaoTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='forcaTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='inteligenciaTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='perspicaciaTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character_effects',
            name='variavelDescricao',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
