# Generated by Django 5.1.6 on 2025-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0005_tela_personagem_carismatotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenMana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenVida',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='regenVigor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
