# Generated by Django 5.1.6 on 2025-04-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0005_alter_tela_personagem_rolagem_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='elementoOutros10',
            new_name='elementoOutros_10',
        ),
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='elementoOutros11',
            new_name='elementoOutros_11',
        ),
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='elementoOutros12',
            new_name='elementoOutros_12',
        ),
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='elementoOutros13',
            new_name='elementoOutros_13',
        ),
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='elementoOutros14',
            new_name='elementoOutros_14',
        ),
        migrations.RenameField(
            model_name='tela_personagem',
            old_name='elementoOutros15',
            new_name='elementoOutros_15',
        ),
    ]
