# Generated by Django 5.1.6 on 2025-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0005_tela_personagem_danofixo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='defesaFixa_1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='defesaFixa_2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='defesaFixa_3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='defesaFixa_4',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='defesaFixa_5',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='resistencia_1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='resistencia_2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='resistencia_3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='resistencia_4',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='resistencia_5',
            field=models.IntegerField(default='0'),
        ),
    ]
