# Generated by Django 5.1.6 on 2025-03-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0006_tela_personagem_defesafixa_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem10',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem11',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem12',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem13',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem14',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem15',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem4',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem5',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem6',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem7',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem8',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem9',
            field=models.IntegerField(default='0'),
        ),
    ]
