# Generated by Django 5.1.6 on 2025-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0006_rename_elementooutros10_tela_personagem_elementooutros_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela_personagem',
            name='mana',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vida',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vigor',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
