# Generated by Django 5.1.6 on 2025-05-07 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0003_base_personagem_carismaper_and_more'),
        ('tela_personagem', '0007_alter_tela_personagem_mana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavelTipo', models.CharField(max_length=50)),
                ('variavelPropriedade', models.CharField(max_length=50)),
                ('variavelValor', models.IntegerField(blank=True, default=0)),
                ('posicao', models.CharField(max_length=50)),
                ('peca', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_personagem.base_personagem')),
            ],
        ),
    ]
