# Generated by Django 5.1.6 on 2025-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0007_tela_personagem_rolagem1_tela_personagem_rolagem10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem16',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem17',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem18',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem19',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem20',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem21',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem22',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem23',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem24',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='rolagem25',
            field=models.IntegerField(default='0'),
        ),
    ]
