# Generated by Django 5.1.6 on 2025-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0008_tela_personagem_rolagem16_tela_personagem_rolagem17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao10',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao11',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao12',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao13',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao14',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao15',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao4',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao5',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao6',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao7',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao8',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='amplificacao9',
            field=models.IntegerField(default='0'),
        ),
    ]
