# Generated by Django 5.1.6 on 2025-05-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0008_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nome',
            name='origem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nome',
            name='peca',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nome',
            name='posicao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nome',
            name='variavelPropriedade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nome',
            name='variavelTipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
