# Generated by Django 5.1.6 on 2025-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0009_alter_nome_origem_alter_nome_peca_alter_nome_posicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nome',
            name='origem',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nome',
            name='peca',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nome',
            name='variavelPropriedade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nome',
            name='variavelTipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
