# Generated by Django 5.1.6 on 2025-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0010_tela_personagem_regenmana_tela_personagem_regenvida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela_personagem',
            name='mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vida',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='tela_personagem',
            name='vigor',
            field=models.IntegerField(default=100),
        ),
    ]
