# Generated by Django 5.1.6 on 2025-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0010_alter_nome_origem_alter_nome_peca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
