# Generated by Django 5.1.6 on 2025-05-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_personagem', '0003_base_personagem_carismaper_and_more'),
        ('tela_personagem', '0011_tela_personagem_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nome',
            new_name='Character_attribute',
        ),
    ]
