# Generated by Django 5.1.6 on 2025-03-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0012_elementos_personagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementos_personagem',
            name='nome',
            field=models.CharField(default='', max_length=30),
        ),
    ]
