# Generated by Django 5.1.6 on 2025-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0012_rename_nome_character_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='carismaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='destrezaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='determinacaoPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='forcaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='inteligenciaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='perspicaciaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
