# Generated by Django 5.1.6 on 2025-03-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0013_elementos_personagem_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='danoFinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='amplificacao9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='danoFixo_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='danoFixo_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='danoFixo_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='defesaFixa_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='defesaFixa_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='defesaFixa_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='defesaFixa_4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='defesaFixa_5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='penetracao_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='penetracao_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='penetracao_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='resistencia_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='resistencia_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='resistencia_3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='resistencia_4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='resistencia_5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem16',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem17',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem18',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem19',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem20',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem21',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem22',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem23',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem24',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem25',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='elementos_personagem',
            name='rolagem9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
