# Generated by Django 5.1.6 on 2025-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0014_tela_personagem_danofinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros10',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros11',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros12',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros13',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros14',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros15',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros3',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros4',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros5',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros6',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros7',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros8',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='elementos_personagem',
            name='outros9',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='outros9',
            field=models.IntegerField(default=0),
        ),
    ]
