# Generated by Django 5.1.6 on 2025-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0015_elementos_personagem_outros1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='dano_espiritual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='reducao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='reducao_espiritual',
            field=models.IntegerField(default=0),
        ),
    ]
