# Generated by Django 5.1.6 on 2025-03-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0016_tela_personagem_dano_espiritual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tela_personagem',
            name='dano_espiritual',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='penetracao_extra',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='reducao',
        ),
        migrations.RemoveField(
            model_name='tela_personagem',
            name='reducao_espiritual',
        ),
    ]
