# Generated by Django 5.1.6 on 2025-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_personagem', '0017_remove_tela_personagem_dano_espiritual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela_personagem',
            name='dano_espiritual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='penetracao_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='reducao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tela_personagem',
            name='reducao_espiritual',
            field=models.IntegerField(default=0),
        ),
    ]
