# Generated by Django 5.1.6 on 2025-04-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_10',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_11',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_12',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_13',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_14',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_15',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_16',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_17',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_18',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_19',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_20',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_21',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_22',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_23',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_24',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_25',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_6',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_7',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_8',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='rolagem_9',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
