# Generated by Django 5.1.6 on 2025-05-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0002_remove_acessorios_amplificacao_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessorios',
            name='mana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='acessorios',
            name='vida',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='acessorios',
            name='vidaBase',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='acessorios',
            name='vigor',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='regenMana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='regenVida',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='regenVigor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
