# Generated by Django 5.1.6 on 2025-04-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0002_remove_acessorios_nome_remove_acessorios_vida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessorios',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
