# Generated by Django 5.1.6 on 2025-04-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0003_acessorios_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorios',
            name='peca',
            field=models.CharField(choices=[('anelAnelar', 'Anel_Anelar'), ('anelIndicador', 'Anel_Indicador'), ('anelMedio', 'Anel_Medio'), ('anelMinimo', 'Anel_Minimo'), ('braceleteEsquerdo', 'Bracelete_Esquerdo'), ('braceleteDireito', 'Bracelete_Direito'), ('brincoEsquerdo', 'Brinco_Esquerdo'), ('brincoDireito', 'Brinco_Direito'), ('acessorioP', 'Acessorio_Principal'), ('acessorioS', 'Acessorio_Secundario'), ('cinturao', 'Cinturao')], default='principal', max_length=25),
        ),
    ]
