# Generated by Django 5.1.6 on 2025-05-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0003_acessorios_mana_acessorios_vida_acessorios_vidabase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessorios',
            old_name='vidaBase',
            new_name='vidaTotal',
        ),
    ]
