# Generated by Django 5.1.6 on 2025-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0004_rename_vidabase_acessorios_vidatotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessorios',
            name='carismaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='acessorios',
            name='destrezaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='acessorios',
            name='determinacaoPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='acessorios',
            name='forcaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='acessorios',
            name='inteligenciaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='acessorios',
            name='perspicaciaPer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
