# Generated by Django 5.1.6 on 2025-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidade', '0002_rename_hab1_custo_habilidade_hab10_1_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='personagem',
            field=models.CharField(default='', max_length=100),
        ),
    ]
