# Generated by Django 5.1.6 on 2025-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidade', '0002_habilidade_hab10_1_tipo_habilidade_hab10_2_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='hab10_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab10_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab10_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab10_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab10_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab10_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab11_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab11_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab11_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab11_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab11_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab11_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab12_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab12_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab12_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab12_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab12_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab12_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab1_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab1_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab1_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab1_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab1_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab1_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab2_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab2_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab2_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab2_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab2_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab2_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab3_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab3_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab3_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab3_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab3_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab3_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab4_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab4_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab4_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab4_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab4_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab4_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab5_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab5_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab5_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab5_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab5_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab5_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab6_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab6_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab6_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab6_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab6_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab6_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab7_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab7_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab7_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab7_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab7_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab7_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab8_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab8_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab8_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab8_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab8_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab8_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab9_1_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab9_2_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab9_3_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab9_4_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab9_5_nivel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab9_6_nivel',
            field=models.TextField(blank=True, default=''),
        ),
    ]
