# Generated by Django 5.1.6 on 2025-03-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidade', '0003_remove_habilidade_carisma_remove_habilidade_destreza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='hab1_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab1_nome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab2_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab2_nome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab3_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab3_nome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab4_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab4_nome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab5_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab5_nome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab6_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab6_nome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab7_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab7_nome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab8_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab8_nome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab9_custo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab9_nome',
            field=models.TextField(default=''),
        ),
    ]
